name: Armor Health

# every push or PR made to any branch, must be
# analyzed
on: [push, pull_request]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:      
  build-win32:
    name: Building (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    # TODO: allow install and test steps to be separate
    - name: Install dependencies and run tests
      run: composer install --prefer-dist --no-progress --no-suggest && composer test
