name: Armor-Lib Health

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Building (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run the tests
      run: composer test

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
      
  build-win32:
    name: Building (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run the tests
      run: composer test
      
# macOS Support will be stopped for now
#   build-darwin:
#     name: Building (macOS)
#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Validate composer.json and composer.lock
#       uses: php-actions/composer@v1
#       with:
#         command: validate
#       # run: composer validate

#     - name: Install dependencies
#       uses: php-actions/composer@v1
#       with:
#         command: install --prefer-dist --no-progress --no-suggest
    
#     - name: Run the tests
#       uses: php-actions/composer@v1
#       with:
#         command: test
